<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>KCLDA.DayongManager</AssemblyName>
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <ApplicationManifest>app.manifest</ApplicationManifest>
	<DefaultItemExcludes>$(DefaultItemExcludes);KCLDA.DayongManager.Mobile\**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.8" />
    <Compile Remove="Properties\AssemblyInfo.cs" />
    <None Include="Data\InitialData.xlsx" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Data\KCLDA-Bylaws.docx" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
